---
- name: exploring line in file
  hosts: planetexpress:!farnsworth

  vars:
  - fileloc: "/var/log/bootstrap.log"

  tasks:
  - name: "Insertalineinto {{ fileloc }}"
    lineinfile:
      path: "{{ fileloc }}"
      regexp: "^Setting up lib.*"
      line: "removedbyansible lineinfile module"
      backup: yes
      become: true
